name: Repro

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  repro:
    name: 'Repro: node permissions error'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node (prism)
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: cli/package-lock.json
          node-version-file: '.tool-versions'
      - run: npm install
